
export const ARIAAbstractRole = {
  command: "command",
  composite:"composite",
  input:"input",
  landmark: "landmark",
  range:"range",
  roletype:"roletype",
  section:"section",
  sectionhead:"sectionhead",
  select:"select",
  structure:"structure",
  widget:"widget",
  window:"window"
};

export const ARIAWidgetRole = {
  alert:"alert",
  alertdialog:"alertdialog",
  button:"button",
  checkbox:"checkbox",
  dialog:"dialog",
  gridcell:"gridcell",
  link:"link",
  log:"log",
  marquee:"marquee",
  menuitem:"menuitem",
  menuitemcheckbox:"menuitemcheckbox",
  menuitemradio:"menuitemradio",
  option:"option",
  progressbar:"progressbar",
  radio:"radio",
  scrollbar:"scrollbar",
  searchbox:"searchbox",
  slider:"slider",
  spinbutton:"spinbutton",
  status:"status",
  switch:"switch",
  tab:"tab",
  tabpanel:"tabpanel",
  textbox:"textbox",
  timer:"timer",
  tooltip:"tooltip",
  treeitem:"treeitem"
};

export const ARIACompositeWidgetRole ={
  combobox:"combobox",
  grid:"grid",
  listbox:"listbox",
  menu:"menu",
  menubar:"menubar",
  radiogroup:"radiogroup",
  tablist:"tablist",
  tree:"tree",
  treegrid:"treegrid"
};

export const ARIADocumentStructureRole = {
  article:"article",
  cell:"cell",
  columnheader:"columnheader",
  definition:"definition",
  directory:"directory",
  document:"document",
  feed:"feed",
  figure:"figure",
  group:"group",
  heading:"heading",
  img:"img",
  list:"list",
  listitem:"listitem",
  math:"math",
  none:"none",
  note:"note",
  presentation:"presentation",
  region:"region",
  row:"row",
  rowgroup:"rowgroup",
  rowheader:"rowheader",
  separator:"separator",
  table:"table",
  term:"term",
  toolbar:"toolbar"
};

export const ARIALandmarkRole = {
  application:"application",
  banner:"banner",
  complementary:"complementary",
  contentinfo:"contentinfo",
  form:"form",
  main:"main",
  navigation:"navigation",
  search:"search",
};

export const ARIADPubRole = { 
  docAbstract:"doc-abstract",
  docAcknowledgments:"doc-acknowledgments",
  docAfterword:"doc-afterword",
  docAppendix:"doc-appendix",
  docBacklink:"doc-backlink",
  docBiblioEntry:"doc-biblioentry",
  docBiliography:"doc-bibliography",
  docBiblioRef:"doc-biblioref",
  docChapter:"doc-chapter",
  docColophon:"doc-colophon",
  docConclusion:"doc-conclusion",
  docCover:"doc-cover",
  docCredit:"doc-credit",
  docCredits:"doc-credits",
  docDedication:"doc-dedication",
  docEndNote:"doc-endnote",
  docEndNotes:"doc-endnotes",
  docEpigraph:"doc-epigraph",
  docEpilogue:"doc-epilogue",
  docErrata:"doc-errata",
  docExample:"doc-example",
  docFootNote:"doc-footnote",
  docForeword:"doc-foreword",
  docGlossary:"doc-glossary",
  docGlossrRef:"doc-glossref",
  docIndex:"doc-index",
  docIntroduction:"doc-introduction",
  docNoteRef:"doc-noteref",
  docNotice:"doc-notice",
  docPageBreak:"doc-pagebreak",
  docPageList:"doc-pagelist",
  docPart:"doc-part",
  docPreface:"doc-preface",
  docPrologue:"doc-prologue",
  docPullQuote:"doc-pullquote",
  docQna:"doc-qna",
  docSubtitle:"doc-subtitle",
  docTip:"doc-tip",
  docToc:"doc-toc",
};

export const  ARIARole ={ 
  ARIAWidgetRole,
  ARIACompositeWidgetRole,
  ARIADocumentStructureRole,
  ARIALandmarkRole
};


export const ARIAState = { 
  ariaBusy:"aria-busy",
  ariaChecked:"aria-checked",
  ariaDisabled:"aria-disabled",
  ariaExpanded:"aria-expanded",
  ariaGrabbed:"aria-grabbed",
  ariaHiddend:"aria-hidden",
  ariaInvalid:"aria-invalid",
  ariaPressed:"aria-pressed",
  ariaSelected:"aria-selected" ,
};

export const ARIAProperty = {
  ariaActiveDescendant:"aria-activedescendant",
  ariaAtomic:"aria-atomic",
  ariaAutoComplete:"aria-autocomplete",
  ariaColCount:"aria-colcount",
  ariaColIndex:"aria-colindex",
  ariaColSpan:"aria-colspan",
  ariaControls:"aria-controls",
  ariaCurrent:"aria-current",
  ariaDescribeDat:"aria-describedat",
  ariaDescribedBy:"aria-describedby",
  ariaDetails:"aria-details",
  ariaDropEffect:"aria-dropeffect",
  ariaErrorMessage:"aria-errormessage",
  ariaFlowTo:"aria-flowto",
  ariaHasPopUp:"aria-haspopup",
  ariaKeyShortCuts:"aria-keyshortcuts",
  ariaLabel:"aria-label",
  ariaLabelledBy:"aria-labelledby",
  ariaLevel:"aria-level",
  ariaLive:"aria-live",
  ariaModal:"aria-modal",
  ariaMultine:"aria-multiline",
  ariaMultiSelectable:"aria-multiselectable",
  ariaOrientation:"aria-orientation",
  ariaOwns:"aria-owns",
  ariaPlaceHolder:"aria-placeholder",
  ariaPosinset:"aria-posinset",
  ariaReadOnly:"aria-readonly",
  ariaRelevant:"aria-relevant",
  ariaRequired:"aria-required",
  ariaRoleDescription:"aria-roledescription",
  ariaRowCount:"aria-rowcount",
  ariaRowIndex:"aria-rowindex",
  ariaRowSpan:"aria-rowspan",
  ariaSetSize:"aria-setsize",
  ariaSort:"aria-sort",
  ariaValueMax:"aria-valuemax",
  ariaValueMin:"aria-valuemin",
  ariaValueNow:"aria-valuenow",
  ariaValueText:"aria-valuetext",
};

export const ARIAPropertyMap = {
  ariaBusy:"aria-busy",
  ariaChecked:"aria-checked",
  ariaDisabled:"aria-disabled",
  ariaExpanded:"aria-expanded",
  ariaGrabbed:"aria-grabbed",
  ariaHidden:"aria-hidden",
  ariaInvalid:"aria-invalid",
  ariaPressed:"aria-pressed",
  ariaSelected:"aria-selected",
  ariaActiveDescendant:"aria-activedescendant",
  ariaAtomic:"aria-atomic",
  ariaAutoComplete:"aria-autocomplete",
  ariaColCount:"aria-colcount",
  ariaColIndex:"aria-colindex",
  ariaColSpan:"aria-colspan",
  ariaControls:"aria-controls",
  ariaCurrent:"aria-current",
  ariaDescribeDat:"aria-describedat",
  ariaDescribedBy:"aria-describedby",
  ariaDetails:"aria-details",
  ariaDropEffect:"aria-dropeffect",
  ariaErrorMessage:"aria-errormessage",
  ariaFlowTo:"aria-flowto",
  ariaHasPopUp:"aria-haspopup",
  ariaKeyShortCuts:"aria-keyshortcuts",
  ariaLabel:"aria-label",
  ariaLabelledBy:"aria-labelledby",
  ariaLevel:"aria-level",
  ariaLive:"aria-live",
  ariaModal:"aria-modal",
  ariaMultine:"aria-multiline",
  ariaMultiSelectable:"aria-multiselectable",
  ariaOrientation:"aria-orientation",
  ariaOwns:"aria-owns",
  ariaPlaceHolder:"aria-placeholder",
  ariaPosinset:"aria-posinset",
  ariaReadOnly:"aria-readonly",
  ariaRelevant:"aria-relevant",
  ariaRequired:"aria-required",
  ariaRoleDescription:"aria-roledescription",
  ariaRowCount:"aria-rowcount",
  ariaRowIndex:"aria-rowindex",
  ariaRowSpan:"aria-rowspan",
  ariaSetSize:"aria-setsize",
  ariaSort:"aria-sort",
  ariaValueMax:"aria-valuemax",
  ariaValueMin:"aria-valuemin",
  ariaValueNow:"aria-valuenow",
  ariaValueText:"aria-valuetext",
};

// const ARIAPropertyDefinition = {
//   type: 'string'
//    'id'
//    'idlist'
//    'integer'
//    'number'
//    'boolean'
//    'token'
//    'tokenlist'
//    'tristate',
// };

export const ARIAPropertyCurrent = {
  page:"page",
  step:"step",
  location:"location",
  date:"date",
  time:"time",
  true:"true",
  false:"false",
};

export default {
  ARIAAbstractRole,
  ARIARole,
  ARIAWidgetRole,
  ARIACompositeWidgetRole,
  ARIADPubRole,
  ARIADocumentStructureRole,
  ARIALandmarkRole,
  ARIAProperty,
  ARIAPropertyCurrent,
  ARIAPropertyMap
};


